# Generated by Django 5.0.3 on 2024-06-03 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'author'], name='blog_commen_post_id_fc2a4f_idx'),
        ),
    ]
